### ISSUE TITLE
Should domain/LDAP be created if it is not specified?

### ISSUE THREAD

**Issue by roweryan** [walkamongus/sssd#8]
My sssd.conf looks like this:

```
[domain/CUSTOM-LDAP]
blah3 = blah
blah2 = blah
blah1 = blah

[domain/LDAP]
cache_credentials = true
id_provider = ldap
```

but it looks like domain/LDAP comes from a default - it's not in my manifest.

**Comment by walkamongus** [comment]
Its a default that gets merged in. It should be harmless but I agree, it would be nice to get rid of it. If you have time to work that up and submit a pull request that would be awesome. Otherwise, it might take me a bit to get to it.

**Comment by Spreadcat** [comment]
Hi. I was stumbling on the same issue. When removing domain/ldap my problems also disappeared and the configuration was working.
I added an additional parameter to the module to allow/disallow the default config. If this approach is OK with you I can send you a pull request.  
Wanted to ask for this anyhow today and saw this issue by accident.

**Comment by walkamongus** [comment]
Hello --yes a pull request would be welcome! Thanks!

**Comment by Spreadcat** [comment]
Pull-request #13 created.

**Comment by walkamongus** [comment]
#13 merged
